name: video_player_mux
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Android (Monitor Mux Data enabled for Android only).
repository: https://github.com/hungryemon/video_player_mux/  #Repository Link
issue_tracker: https://github.com/hungryemon/video_player_mux/issues #Issues
version: 1.0.2

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: video_player_android_mux


dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.4
  #Android Implementation
  video_player_android_mux: ^1.0.2
  #Video Player Interface
  video_player_platform_interface_mux: ^1.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
